<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RetreatUI_Launcher</AssemblyName>
    <RootNamespace>RetreatUI.Launcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\RetreatUI_Launcher.ico</ApplicationIcon>
    <Version>0.2.8</Version>
    <FileVersion>0.2.8.0</FileVersion>
    <AssemblyVersion>0.2.8.0</AssemblyVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\RetreatUI_Launcher.ico" />
    <Resource Include="Assets\RetreatUI_Launcher_256.png" />
  </ItemGroup>
</Project>
